Revert "refactor(rooch-store): rename DA block cursor constant (#2797)"
This reverts commit b3870af384ba45f99f9f7cd7b07f730c6f7abd08.

this commit cause:
 Error: Invalid argument: Column families not opened: da_last_block_number

and rocksdb cannot be opened correctly