fix(statedb): fix export genesis error caused by object struct changes (#2244)
## Summary

### Original Error

```
Error: CSV error: found record with 1 fields, but the previous record has 2 fields
```

### Fix

The issue was fixed by exporting `(FieldKey, ObjectState)`.

### Refine Codes

1. general init_job() used, simplifies both of the initialization of genesis jobs and export tasks
2. utilize instant time instead of system time for recording time cost