fix(indexer/rebuild): switch to Tokio for threading in rebuild.rs (#2436)
Replace std::thread with tokio::task::spawn_blocking for producing and applying updates. This improves asynchronous handling and integrates better with the Tokio runtime.

fixed this when rebuild:

```shell
2024-08-14T21:58:40.926122Z INFO rooch::commands::indexer::commands::rebuild: indexer rebuild started
thread '<unnamed>' panicked at crates/rooch-indexer/src/indexer_reader.rs:119:13:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Indexer rebuild task finished(0 updates applied) in: 21.674956ms
Error: Produce updates error
```